# Generated by Django 5.2.1 on 2025-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='healthy.jpg', upload_to='myapp/static/post_images/'),
            preserve_default=False,
        ),
    ]
